### ISSUE TITLE
ActiveModel::ForbiddenAttributesError on Rails 4.2

### ISSUE THREAD

**Issue by hector** [FooBarWidget/default_value_for#61]
For a simple model

``` ruby
class Foo < ActiveRecord::Base
  default_value_for :my_attr, 'my_value'
end
```

This works:

``` ruby
Foo.create
```

But what is typically called in the controller raises `ActiveModel::ForbiddenAttributesError`. Example:

``` ruby
Foo.create ActionController::Parameters.new
```

**Comment by aripollak** [comment]
This doesn't seem related to default_value_for? http://edgeguides.rubyonrails.org/action_controller_overview.html#strong-parameters

**Comment by hector** [comment]
The default value should be set internally from the model itself, it is not passed as a parameter in the `Model.new` or `Model.create` method. There is no reason why when using `ActionController::Parameters` it crashes, it just shouldn't.

**Comment by pedrofurtado** [comment]
@FooBarWidget I think this issue can be closed.

**Comment by chrisarcand** [comment]
Thanks @pedrofurtado 

For posterity, I would expect the original code example above to behave exactly that way. `Foo.create ActionController::Parameters.new` would raise that exception because no parameters are being permitted (strong parameters). It's not default_value_for's job to override Rails and let you create a record with unpermitted parameters just because you have a default set.
