### ISSUE TITLE
Is compatible with Rails 6?

### ISSUE THREAD

**Issue by pedrofurtado** [FooBarWidget/default_value_for#80]
Rails 6 is coming, and it will be great to make gem compatible with it (even if Rails 6 is still in beta, alpha, and so on) :+1:

**Comment by chrisarcand** [comment]
Hello!

Rails 6 is indeed due at the end of this month. The gemspec for this gem is intentionally set to allow for beta releases of the next version of Rails, and you should be able to at least include it in a Gemfile for testing purposes already. Please post any specific issues (if any) you encounter and I'll be happy to take a look at them.

Otherwise, we'll wait until the release actually happens and we can verify the final cut of Rails 6.0 works with the gem to loosen the gemspec to allow for 6.0 itself.

Thanks!

**Comment by Sexual** [comment]
Rails 6 has now been released.

**Comment by pedrofurtado** [comment]
@chrisarcand @FooBarWidget Rails 6 is released! Could you reopen the issue to test gem against Rails final 6.x version? 🎉 🤝

**Comment by vinc** [comment]
I have been using this gem and rails 6.0.0 rc2 in production on a big app for almost a month now and rc1 before that, so a new release will be appreciated as it's the only gem blocking the upgrade to rails 6.0.0 on my app. Thanks 👍

**Comment by kapso** [comment]
Rails 6 please, thanks : )

**Comment by cfanpnk** [comment]
This is blocking our Rails 6 upgrade as well. Could you take another look at this? Many thanks!

**Comment by pedrofurtado** [comment]
@FooBarWidget @norman @chrisarcand

**Comment by chrisarcand** [comment]
Patience, please. Not everyone spends their weekend doing OSS. Moving conversation to #82
